"""empty message

Revision ID: 17cff1075664
Revises: 179b663b5d47
Create Date: 2022-11-12 11:50:05.231876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cff1075664'
down_revision = '179b663b5d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_messages', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('channel_messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('channel_messages', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
